export const ADD_PATIENT = 'ADD_PATIENT';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SET_DATA_LOCALLLY =  'SET_DATA_LOCALLLY';
export const LOCAL_DATA_SUCCESS =  'LOCAL_DATA_SUCCESS';
export const DELETE =  'DELETE' ;
export const DELETE_SUCCESS =  'DELETE_SUCCESS' ;

export const GET_PATIENT =  'GET_PATIENT' ;
export const GET_PATIENT_SUCCESS =  'GET_PATIENT_SUCCESS' ;
